# Generated by https://www.mockaroo.com/

insert into user_link (id, github, linkedin, youtube) values (1, 'http://github.com/1', 'https://linkedin.com/1', 'http://youtube.com/1');
insert into user (id, first_name, last_name, user_link_id) values (1, 'Woodman', 'Penwright', 1);

insert into user_link (id, github, linkedin, youtube) values (2, 'http://github.com/2', 'https://linkedin.com/2', 'http://youtube.com/2');
insert into user (id, first_name, last_name, user_link_id) values (2, 'Bryon', 'Russ', 2);

insert into user_link (id, github, linkedin, youtube) values (3, 'http://github.com/3', 'https://linkedin.com/3', 'http://youtube.com/3');
insert into user (id, first_name, last_name, user_link_id) values (3, 'Julee', 'Cooke', 3);