# Generated by https://www.mockaroo.com/

insert into user_link (id, github, linkedin, youtube) values (1, 'http://github.com', 'https://linkedin.com', 'http://youtube.com');
insert into user (id, first_name, last_name, user_link_id) values (1, 'Woodman', 'Penwright', 1);

insert into user_link (id, github, linkedin, youtube) values (2, 'http://github.com', 'https://linkedin.com', 'http://youtube.com');
insert into user (id, first_name, last_name, user_link_id) values (2, 'Bryon', 'Russ', 2);

insert into user_link (id, github, linkedin, youtube) values (3, 'http://github.com', 'https://linkedin.com', 'http://youtube.com');
insert into user (id, first_name, last_name, user_link_id) values (3, 'Julee', 'Cooke', 3);