# Generated by https://www.mockaroo.com/
insert into user (id, first_name, last_name) values (1, 'Woodman', 'Penwright');
insert into user (id, first_name, last_name) values (2, 'Bryon', 'Russ');
insert into user (id, first_name, last_name) values (3, 'Julee', 'Cooke');
insert into user (id, first_name, last_name) values (4, 'Case', 'Bour');
insert into user (id, first_name, last_name) values (5, 'Colan', 'Siggee');
insert into user (id, first_name, last_name) values (6, 'Sigismond', 'Munby');
insert into user (id, first_name, last_name) values (7, 'Brittney', 'Winwright');
insert into user (id, first_name, last_name) values (8, 'Wolf', 'Potteridge');
insert into user (id, first_name, last_name) values (9, 'Minerva', 'Pencott');
insert into user (id, first_name, last_name) values (10, 'Celia', 'Greeve');